version: '3'

services:
  dafiti_challenge:
    build:
      context: .
    image: dafiti_challenge
    container_name: dafiti_challenge
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dafiti_challenge
    ports:
      - "5432:5432"
