# Generated by Django 4.1.1 on 2022-09-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes", "0002_alter_shoes_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoes",
            name="image",
            field=models.ImageField(upload_to="product_images"),
        ),
    ]
